name: report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install LaTeX and dependencies
      run: sudo apt install -y texlive-latex-extra texlive-science texlive-lang-portuguese latexmk curl

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: report1
      run: |
        cd report
        latexmk -f -pdf main.tex

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: report/report.pdf
